Update Button Device capability to work with HE
HubitatCommunity/InfluxDB-Logger pull request #42
Opened 2023-01-25 23:06 UTC by Mavrrick

I noticed that no button devices were showing up in HE. The input selection was looking at a capability that was deprecated on HE. I updated it to pushableButton which is currently valid and then updated the section that manages the subscriptions for attributes to subscribe to the various possible button events.

2023-01-26 16:38 UTC, dennypage commented
Does anything need to be updated with the processing of the event in lines 408-413?

2023-01-26 17:07 UTC, Mavrrick commented
Lines 408-413 are written for a different way of functioning in ST. It looks like that capability would report Held and release as part of the button press event. I would think those lines could posibly be removed. With HE those are all their own event and wouldn't report this way.

That said one thing I just noticed is that the value provided with the Pushed event represents the Button number of the device. These are also momentary events. This isn't really a how long is it double tapped or single tapped just that it happened. This is really a device that is hurt by soft Polling again because it is a momentary device. I don't t hink this is really a graphable item. it would be more for simply listing the events when they happen. What are your thoughts

2023-02-22 05:54 UTC, dennypage approved these changes

2023-02-23 20:37 UTC, dennypage requested changes
You pushed the help guide on top of the button change. Please pull the help guide from the PR please. Thanks.

2023-02-26 22:02 UTC, dennypage approved these changes

2023-02-26 22:02 UTC, merged